- alias: "Update Available Notification"
  hide_entity: True
  trigger:
    platform: state
    entity_id: updater.updater

  condition:
    - condition: template
      value_template: "{{ states('updater.updater') != 'unknown' }}"

  action:
    - service: script.notify_engine
      data_template:
        value1: 'There is a new Version of Home-Assistant Available.'
        value2: "{{ states('updater.updater') }}"
        who: 'patrick'
