homeassistant:
  name: Thuis
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: metric
  time_zone: Europe/Amsterdam
  customize: !include_dir_merge_named customize
  customize_domain:
    automation:
      initial_state: 'on'
  customize_glob:
    "automation.*watchdog*":
      icon: mdi:timer
  packages: !include_dir_named packages

http:
  base_url: !secret http_base_url
  # server_port: !secret http_port
  api_password: !secret http_api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  # trusted_networks:
  #   - 192.168.10.0/24
  #   - !secret external_ip
  ip_ban_enabled: True
  login_attempts_threshold: 3

frontend:
  javascript_version: auto

# panel_custom:
#   - name: floorplan
#     sidebar_title: Alarm Panel
#     sidebar_icon: mdi:security-home
#     url_path: floorplan
#     config:
#       hide_app_toolbar:
#       config: /local/custom_ui/floorplan/floorplan.yaml
#
#   - name: clock
#     sidebar_title: Alarm Clock
#     sidebar_icon: mdi:alarm
#     url_path: clock
#     config:
#       hide_app_toolbar:
#       config: /local/custom_ui/floorplan/floorclock.yaml

notify:
  - platform: pushbullet
    api_key: !secret pushbullet_api_key
    name: pushbullet

updater:
  reporting: no
  include_used_components: true

sun:

light:
  - platform: limitlessled
    bridges:
      - host: 192.168.2.20
        version: 5
        port: 8899
        groups:
        - number: 1
          type: rgbw
          name: overloop_plafondlamp
        - number: 2
          type: rgbw
          name: woonkamer_tvmeubel

  - platform: rfxtrx
    automatic_add: False
    devices:
      0b11000000A0A03101010f70:
        name: woonkamer_vensterbank
        fire_event: False
      0b11000000A0A04101010f70:
        name: woonkamer_hanglamp
        fire_event: False
      0b11000000A0A05101010f70:
        name: gang_vloerspotjes
        fire_event: False
      0b11000000A0A02101010f70:
        name: bijkeuken_plafondlamp
        fire_event: False

  - platform: mqtt_json
    name: "MS1 LED"
    state_topic: "multisensor/bijkeuken"
    command_topic: "multisensor/bijkeuken/set"
    brightness: true
    flash: true
    rgb: true
    optimistic: false
    qos: 0

  - tradfri:
    host: 192.168.2.19


# logbook:
#   exclude:
#     entities:
#       - automation.detect_lights_and_adjust_the_brightness_when_turned_on_based_on_time
#       - automation.cuckoo_clock
#       - binary_sensor.office_motion
#       - group.garage_doors
#       - media_player.LivingRoomCC
#       - py.warnings
#       - sensor.since_last_boot
#       - sensor.since_last_boot_templated
#       - sensor.small_garage_status
#       - sensor.large_garage_status
#       - sensor.small_garage_time_in_state
#       - sensor.large_garage_time_in_state
#       - sensor.large_garage_wifi_signal_strength
#       - sensor.small_garage_wifi_signal_strength
#       - sensor.small_garage_reflection_rate
#       - sensor.large_garage_reflection_rate
#       - sensor.pihole_ads_blocked_today
#       - sensor.pihole_ads_percentage_blocked_today
#       - sensor.pihole_dns_queries_today
#       - sensor.time
#       - sensor.date
#       - sensor.floorplan_date
#       - sensor.floorplan_time
#       - sensor.ha_uptime
#
# history:
#   include:
#     domains:
#       - sensor
#       - switch
#       - media_player
#       - light
#       - binary_sensor
#       - cover
#
#   exclude:
#     entities:
#      - sensor.last_boot
#      - sensor.date
#      - sensor.pihole_ads_blocked_today
#      - sensor.pihole_ads_percentage_blocked_today
#      - sensor.pihole_dns_queries_today
#      - sensor.since_last_boot
#      - sensor.since_last_boot_templated
#      - sensor.floorplan_date
#      - sensor.floorplan_time
#      - sensor.ha_uptime
#      - sensor.time
#
# logger: !include logger.yaml
# recorder: !include recorder.yaml

mqtt:
  broker: 127.0.0.1
  port: 1883
  client_id: home-assistant
  username: !secret MQTT_username
  password: !secret MQTT_password

media_player:
  - platform: cast
  - platform: sonos

tts:
  - platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_ID
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: 'us-east-2'
    text_type: ssml
    cache: True
    voice: Ruben
#    cache_dir: /data/tts

# cover:
#   platform: opengarage
#   covers:
#       garage:
#         host:  192.168.2.29
#         device_key: secret
#         name:  Garagepoort

group: !include_dir_merge_named group
device_tracker: !include_dir_merge_list device_tracker
sensor: !include_dir_merge_list sensor
automation: !include_dir_merge_list automation
scene: !include_dir_merge_list scene
switch: !include_dir_merge_list switch
script: !include_dir_merge_named script
input_boolean: !include_dir_merge_named input_boolean
shell_command: !include_dir_merge_named shell_command
