##########  ############################################################
##  Announce when people come or go.
## Announce over all Chromecast Audios
######################################################################
- alias: 'People Greeting'

  trigger:
    - platform: state
      entity_id:
        - device_tracker.patrick
        - device_tracker.nicole
      from: 'not_home'
      to: 'home'
      for: '00:02:00'

  action:
    - service: script.speech_engine
      data_template:
        personarriving: >
          {% set person = trigger.entity_id.split('.')[1]|replace('_', ' ')%}
          {%- macro greeting_sentence(person) -%}
          {{ [
          "Welkom thuis " ~ person,
          "Raad eens wie er thuis is? Het is " ~ person +" !",
          person + " is thuis."
          ] | random }}
          {%- endmacro -%}
          {{greeting_sentence(person)}}
        call_responsibilities: 1
        call_no_announcement: 1
        call_garage_check: 1
        call_window_check: 1
