##############################################################################
###  New Device has connected to the network.  let everyone know.
##############################################################################

- alias: "New device connected"
  trigger:
    - platform: event
      event_type: device_tracker_new_device

  action:
    - wait_template: >-
        {{ not is_state('media_player.woonkamer', 'playing') }}

    - service: script.speech_engine
      data_template:
        NewDevice: "Attentie, er is een nieuw apparaat gedetecteerd op het netwerk."
##############################################################################
