###################################################
## Pricewatch sensors
###################################################

- platform: gearbest
  currency: EUR
  items:
    - url: https://www.gearbest.com/alarm-systems/pp_659226.html
      name: Xiaomi Aqara Human Body Sensor
    - url: https://www.gearbest.com/access-control/pp_626702.html
      name: Xiaomi Aqara Temperature Humidity Sensor
    - url: https://www.gearbest.com/access-control/pp_626703.html
      name: Xiaomi Aqara Window Door Sensor
