- platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
#    - summary
#    - precip_type
    - precip_intensity
    - precip_intensity_max
    - temperature
#    - dew_point
    - wind_speed
#    - wind_bearing
    - cloud_cover
    - humidity
#    - nearest_storm_distance
    - minutely_summary
#    - pressure
#    - visibility
#    - ozone
    - uv_index

- platform: buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - groundtemperature
    - windspeed
    - windforce
    - winddirection
    - windazimuth
    - pressure
    - visibility
    - windgust
    - precipitation
    - irradiance
    - precipitation_forecast_average
    - precipitation_forecast_total


- platform: moon
