#-------------------------------------------
# @CCOSTAN
# Original Repo : https://github.com/CCOSTAN/Home-AssistantConfig
# Neato Support for D7 Connected Botvac - control my [Neato Vacuum](http://amzn.to/2kqnnqu) with Home Assistant.
#-------------------------------------------
homeassistant:
  customize_glob:
    "*.carlojuice*":
      emulated_hue_hidden: True
      homebridge_hidden: True
      hidden: False
#-------------------------------------------
juicenet:
    access_token: !secret juicenet_access_token

group:
  juicenet:
    name: JuiceBox Charger
    control: hidden
    entities:
      - sensor.carlojuice_amps
      - sensor.carlojuice_charge_time
      - sensor.carlojuice_charging_status
      - sensor.carlojuice_energy_added
      - sensor.carlojuice_temperature
      - sensor.carlojuice_voltage
      - sensor.carlojuice_watts

#############################################################################
###  Automations - Alerts related to the JuiceBox (http://amzn.to/2AZVQ37)
##############################################################################
automation:
  - alias: 'Car Charging Alerts'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.carlojuice_charging_status

    action:
      - service: script.notify_engine
        data_template:
          value1: "The Garage charger is now in {{ states('sensor.carlojuice_charging_status') }} mode."
          who: 'parents'

  - alias: 'JuiceBox AMP Alert!'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.carlojuice_amps
        above: 25
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.alert_mode

      - service: script.notify_engine
        data_template:
          value1: "The Juice Box Charger is pulling {{ states('sensor.carlojuice_amps') }} AMPs.  This is above the safety mark of 30.  Please unplug charger immediately."
          who: 'parents'

      - service: script.speech_engine
        data_template:
          value1: "The Juice Box Charger is pulling {{ states('sensor.carlojuice_amps') }} AMPs.  This is above the safety mark of 30.  Please unplug charger immediately."

  - alias: 'JuiceBox Tweet Stat!'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.carlojuice_charge_time
    action:
      - delay: '0{{ range(0,4) | random | int }}:{{ range(10,59) | random | int }}:00'
      - service: script.tweet_engine
        data_template:
          tweet: >
            {{ [
            "The #Chevy Bolt Charged for {{states.sensor.carlojuice_charge_time.state  | int /60/60 }} hours.",
            "The last charging session was {{states.sensor.carlojuice_charge_time.state  | int /60 }} minutes. ",
            "The Juice Box Pro charged the #Chevy #BoltEV for {{states.sensor.carlojuice_charge_time.state  | int /60 }} minutes."
            ] | random + " (http://amzn.to/2zlQIUI) #Electric #Solar"}}
